name: thumbnailer
version: '2.4'
summary: Daemon and admin tool to create and cache image thumbnails for media files
description: >
  This snap provides thumbnailer-service, a DBus daemon that extracts thumbnails from
  local media files and retrieves music album artwork from dash.ubuntu.com. It also
  includes thumbnailer-admin, a command-line utility that allows for basic cache
  maintenance and testing. See lp:thumbnailer for more detail.
grade: devel
confinement: strict

slots:
  thumbnailer:
    interface: dbus
    name: com.canonical.Thumbnailer
    bus: session

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform
  network-manager:
    interface: network-manager
  thumbnails:
    interface: dbus
    name: com.canonical.Thumbnailer
    bus: session

apps:
  thumbnailer-service:
    command: desktop-launch $SNAP/lib/thumbnailer/thumbnailer-service
    # TODO: Currently cannot use a simple daemon with the session bus. For now,
    # the service must be started by hand. See https://github.com/snapcore/snapd/pull/2592
    # daemon: simple
    plugs:
      - platform
      - network
      # TODO: This grants more privileges than we really need but, without this, apparmor
      # denies access.
      - network-manager
      # TODO: The gsettings interface currently does not permit reading.
      # See https://bugs.launchpad.net/snappy/+bug/1600154
      # For now, the service uses default settings because it's gsettings lookups fail.
      - gsettings
      - home
    slots:
      - thumbnailer
  thumbnailer-admin:
    command: desktop-launch $SNAP/bin/thumbnailer-admin
    plugs:
      - platform
      - thumbnails
      - home

parts:
  thumbnailer:
    plugin: cmake
    configflags:
      - -DSNAP_BUILD=1
    source: .
    after:
      - desktop-ubuntu-app-platform
    stage-packages:
        - gstreamer1.0-libav
    filesets:
      binaries:
        - bin/*
        - lib/thumbnailer/*
      man:
        - share/man/*
      etc:
        - etc/*
      share:
        # TODO: This does not seem to have any effect. It is unclear right now how gsettings
        # schemas need to be installed.
        - share/glib-2.0/*
      gstreamer:
        # Libraries needed by the gstreamer plugins we use. Gstreamer loads these with dlopen(),
        # and snapcraft doesn't analyze their dependencies, so we need to include the required
        # libraries explicitly here.
        - usr/lib/*/gstreamer-1.0/*
        - usr/lib/*/libass*
        - usr/lib/*/libavcodec*
        - usr/lib/*/libavfilter*
        - usr/lib/*/libavformat*
        - usr/lib/*/libavresample*
        - usr/lib/*/libavutil*
        - usr/lib/*/libbluray*
        - usr/lib/*/libbs2*
        - usr/lib/*/libcrystalhd*
        - usr/lib/*/libfaad*
        - usr/lib/*/libflite*
        - usr/lib/*/libfribidi*
        - usr/lib/*/libgme*
        - usr/lib/*/libgsm*
        - usr/lib/*/libmodplug*
        - usr/lib/*/libmp3lame*
        - usr/lib/*/libnuma*
        - usr/lib/*/libopencv*
        - usr/lib/*/libopenjpeg*
        - usr/lib/*/libpostproc*
        - usr/lib/*/libschroedinger*
        - usr/lib/*/libshine*
        - usr/lib/*/libsodium*
        - usr/lib/*/libsoxr*
        - usr/lib/*/libssh-gcrypt*
        - usr/lib/*/libsw*
        - usr/lib/*/libtbb*
        - usr/lib/*/libtwolame*
        - usr/lib/*/libva*
        - usr/lib/*/libx26*
        - usr/lib/*/libxvidcore*
        - usr/lib/*/libzmq*
        - usr/lib/*/libzvbi*
    prime:
      - $binaries
      - $man
      - $etc
      - $share
      - $gstreamer
      - ubuntu-app-platform
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/ubuntu-app-platform
