name: thumbnailer
version: '2.4'
summary: Daemon and admin tool to create and cache image thumbnails for media files
description: >
  This snap provides thumbnailer-service, a DBus daemon that extracts thumbnails from
  local media files and retrieves music album artwork from dash.ubuntu.com. It also
  includes thumbnailer-admin, a command-line utility that allows for basic cache
  maintenance and testing. See lp:thumbnailer for more detail.
grade: devel
confinement: strict

slots:
  thumbnailer:
    interface: dbus
    name: com.canonical.Thumbnailer
    bus: session

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform
  network-manager:
    interface: network-manager
  thumbnails:
    interface: dbus
    name: com.canonical.Thumbnailer
    bus: session

apps:
  thumbnailer-service:
    command: desktop-launch $SNAP/lib/thumbnailer/thumbnailer-service
    # TODO: Currently cannot use a simple daemon with the session bus. For now,
    # the service must be started by hand. See https://github.com/snapcore/snapd/pull/2592
    # daemon: simple
    plugs:
      - platform
      - network
      # TODO: This grants more privileges than we really need but, without this, apparmor
      # denies access.
      - network-manager
      # TODO: The gsettings interface currently does not permit reading.
      # See https://bugs.launchpad.net/snappy/+bug/1600154
      # For now, the service uses default settings because it's gsettings lookups fail.
      - gsettings
      - home
    slots:
      - thumbnailer
  thumbnailer-admin:
    command: desktop-launch $SNAP/bin/thumbnailer-admin
    plugs:
      - platform
      - thumbnails
      - home

parts:
  thumbnailer:
    plugin: cmake
    configflags:
      - -DSNAP_BUILD=1
    source: .
    after:
      - desktop-ubuntu-app-platform
    build-packages:
        - gstreamer1.0-libav  # For H.264
        - libgpm2             # Needed by gstreamer1.0-libav
    filesets:
      binaries:
        - bin/*
        - lib/thumbnailer/*
      man:
        - share/man/*
      etc:
        - etc/*
      share:
        # TODO: This does not seem to have any effect. It is unclear right now how gsettings
        # schemas need to be installed.
        - share/glib-2.0/*
      gstreamer:
        # Libraries needed by the gstreamer plugins we use. Gstreamer loads these with dlopen().
        - usr/lib/*/gstreamer-1.0/libgstlibav.so
        - usr/lib/*/libgpm.so.2
    prime:
      - $binaries
      - $man
      - $etc
      - $share
      - $gstreamer
      - ubuntu-app-platform
    install: |
      # Make sure we have a mount point for ubuntu-app-platform
      mkdir -p $SNAPCRAFT_PART_INSTALL/ubuntu-app-platform
      # Copy the libav plugin to the prime, so snapcraft runs ldd over it
      # and adds the dependencies of libgstlibav.so to the prime.
      plugin_dir=$(echo /usr/lib/*/gstreamer-1.0)
      mkdir -p $SNAPCRAFT_PART_INSTALL/$plugin_dir
      plugin=$plugin_dir/libgstlibav.so
      cp $plugin $SNAPCRAFT_PART_INSTALL/$plugin_dir
      # Similar for libgpm2.so, which is a dependency of libav.
      libgpm=$(echo /usr/lib/*/libgpm.so.2)
      cp $libgpm $SNAPCRAFT_PART_INSTALL/$libgpm
